### ISSUE TITLE
Where are the sample API and Provider projects?

### ISSUE THREAD

**Issue by dleangen** [bndtools/bndtools.workspace.min#1]
Hi Peter,

I cloned the workspace, but I don't see the example API and Provider projects. Am I in the wrong project?

**Comment by pkriens** [comment]
They are in a dependency: biz.aQute.osgi.templates. 

I wanted to keep the bndtools.workspace.min as small as possible. The templates are in the biz.aQute.osgi.util repo.

Kind regards,

	Peter Kriens
