### ISSUE TITLE
Version number in build.bnd file

### ISSUE THREAD

**Issue by dleangen** [bndtools/bndtools.workspace.min#2]
In this line:

https://github.com/bndtools/bndtools.workspace.min/blob/e205447e846198ff42b1ac7e34acfe1f8aea0d01/cnf/build.bnd#L2

the version number is provided, which creates the default version number for all projects.

Is the intent:

1. To create a default, which will normally be overridden in the project? Or,
2. To make all of the projects in the workspace have the same version?

**Comment by pkriens** [comment]
I came to the conclusion that it is just a lot easier to have one version in the workspace. Although in rare cases (like wrappers) you can override it, the bundle version is just not that relevant. The important version is the package. So having one version for the workspace is a lot easier. And easy is good :-)

**Comment by dleangen** [comment]
Ok, makes sense.
