### ISSUE TITLE
Consider updating to JUnit5

### ISSUE THREAD

**Issue by dleangen** [bndtools/bndtools.workspace.min#3]
The current workspace uses the enRoute wrapper for JUnit4.

Now that JUnit5 is out, consider updating to support JUnit5.

**Comment by pkriens** [comment]
It is the JUnit 4.13, which is quite new. bnd is updating to support JUnit 5 but it still seems a bit in flux and I've not had personal experience yet.

**Comment by dleangen** [comment]
Ok, no worries. Thanks!
