### ISSUE TITLE
Using private workspace as template?

### ISSUE THREAD

**Issue by dleangen** [bndtools/bndtools.workspace.min#5]
Hey Peter,

This is really nice. I made my own custom template based on a fork of this workspace, so hopefully I can follow along with updates and also keep my customizations.

It was very easy to install the template in my Eclipse and apply it to my workspace. I also noticed that it is even possible to update the workspace easily. You can even see the diffs (at the file level) and apply which changes you want (or don't).

All this is very nice!!

However, it seems to only work for a public workspace.

Is there any plan to make this feature work for a private workspace? The reason is that it would allow a leg up getting started, even though the configurations may contain information that should not be made public.

For now I just made the information very generic in my public workspace, but then I have to manually edit it once I install the workspace, which kind of (at least partially) defeats the purpose of having a custom workspace in the first place.

**Comment by pkriens** [comment]
Why doesn't it work for a private workspace?

**Comment by dleangen** [comment]
When I try to set it up, it will not validate. No details are provided. Please see image.
<img width="531" alt="ss" src="https://user-images.githubusercontent.com/9663141/73498322-57167600-4400-11ea-9a94-6b84ca58d6f2.png">

**Comment by pkriens** [comment]
Did you add your credentials into ~/.bnd/connection-settings.xml?

You can create a personal access token  on Github as password instead of using your github password: https://github.com/settings/tokens. This is highly recommended.

bnd has a `com info <url>` command that verifies your settings against a url. Use with `bnd -d com info <url>` if you need to debug. You can also do `bnd com settings`.

See https://bnd.bndtools.org/instructions/connection-settings.html for some more info.

**Comment by dleangen** [comment]
Ah!

Ok, so how can I use the settings without messing with this?

```
-connection-settings: \
	${if;${pwd};server;maven}; \
		id=${nexus.base}; \
		username=${usr}; \
		password=${pwd}, \
		-bnd
```

I think that the settings in my file are being ignored because of this.

**Comment by pkriens** [comment]
I think you can just remove the - sign before bnd and then enter the credentials in ~/.bnd/connection-settings, or add them in the same way by adding a new clause in this property.

Again `bnd com settings|info <url>' is your friend. Make sure you're inside the workspace.

Kind regards,

	Peter Kriens

**Comment by dleangen** [comment]
Thanks, Peter.

The only thing I can think of is that the password is not being sent along correctly...

Here is the output of `bnd com info https://github.com`:

```
tofino$ bnd com info https://github.com
URI https://github.com
Handled by Server [ match=https://github.com, handler=BasicAuthentication [password=******, user=dleangen], https=HttpsVerification [verify=false, certificatesPath=null]]
Cache file /Users/dleangen/.bnd/urlcache/shas/BLAH.content
Last Modified 1970-01-01T00:00:00Z
Response code 200
State UPDATED
Tag W/"somestring"
Has Payload true
```

The test seems to give a positive result.

The password shown above is *not* what I entered into the connection-settings.xml file. Otherwise, I'm out of ideas...

**Comment by pkriens** [comment]
Yup, bug in bnd :-(

The Github templates support creates a client out of the blue. The client should be parameterized by the workspace. I'll fix this. Until then no private templates :-(

Kind regards,

	Peter Kriens

**Comment by dleangen** [comment]
Ok, thanks! Sometimes it's hard to know if I'm being dense, or if there is a bug. Since this occurs on a daily basis, I am often questioning my sanity.

At least on this one I am not crazy. Yay.

I'll keep this issue open until there is a fix.
